#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# home:
#     path: /public
#     controller: App\Controller\PublicController::home

# login:
#     path: /public/login
#     controller: App\Controller\PublicController::login

